// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateServer(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.Server>;

export function DeleteServer(arg1:string):Promise<void>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetServers():Promise<Array<models.Server>>;

export function Greet(arg1:string):Promise<string>;

export function UpdateServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<models.Server>;

export function ValidateServerPath(arg1:string):Promise<Record<string, any>>;
