// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {services} from '../models';
import {models} from '../models';
import {config} from '../models';
import {mods} from '../models';
import {thunderstore} from '../models';
import {system} from '../models';

export function ClearLogs():Promise<void>;

export function CreateBackup(arg1:string,arg2:string):Promise<backup.Backup>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<services.ModProfile>;

export function CreateServer(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.Server>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string,arg2:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function ExportLogs(arg1:string):Promise<string>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetAppUptime():Promise<number>;

export function GetBepInExPlugins(arg1:string):Promise<Array<string>>;

export function GetDefaultConfig():Promise<config.ServerConfig>;

export function GetInstalledMods(arg1:string):Promise<Array<mods.InstalledMod>>;

export function GetLogs():Promise<Array<string>>;

export function GetModDetail(arg1:string,arg2:string):Promise<thunderstore.Package>;

export function GetProcessInfo(arg1:number):Promise<system.ProcessInfo>;

export function GetProfiles(arg1:string):Promise<Array<services.ModProfile>>;

export function GetServerPID():Promise<number>;

export function GetServers():Promise<Array<models.Server>>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function Greet(arg1:string):Promise<string>;

export function InstallBepInEx(arg1:string):Promise<void>;

export function InstallMod(arg1:string,arg2:thunderstore.Package,arg3:thunderstore.Version):Promise<void>;

export function InstallSteamCMD():Promise<void>;

export function InstallValheimServer(arg1:string):Promise<void>;

export function IsBepInExInstalled(arg1:string):Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function IsSteamCMDInstalled():Promise<boolean>;

export function ListBackups(arg1:string):Promise<Array<backup.Backup>>;

export function LoadServerConfig(arg1:string):Promise<config.ServerConfig>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function RunSafetyChecks(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<Array<services.SafetyCheck>>;

export function SaveServerConfig(arg1:string,arg2:config.ServerConfig):Promise<void>;

export function SearchMods(arg1:string,arg2:number):Promise<Array<thunderstore.Package>>;

export function SetLogPaused(arg1:boolean):Promise<void>;

export function SetModEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StartServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:boolean,arg7:string):Promise<void>;

export function StopServer():Promise<void>;

export function UninstallMod(arg1:string,arg2:string):Promise<void>;

export function UpdateServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<models.Server>;

export function ValidateServerPath(arg1:string):Promise<Record<string, any>>;
