// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}
