// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function CreateBackup(arg1, arg2) {
  return window['go']['app']['App']['CreateBackup'](arg1, arg2);
}

export function CreateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateProfile'](arg1, arg2, arg3, arg4);
}

export function CreateServer(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateServer'](arg1, arg2, arg3, arg4);
}

export function DeleteBackup(arg1) {
  return window['go']['app']['App']['DeleteBackup'](arg1);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['app']['App']['DeleteProfile'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['app']['App']['DeleteServer'](arg1);
}

export function ExportLogs(arg1) {
  return window['go']['app']['App']['ExportLogs'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAppUptime() {
  return window['go']['app']['App']['GetAppUptime']();
}

export function GetBepInExPlugins(arg1) {
  return window['go']['app']['App']['GetBepInExPlugins'](arg1);
}

export function GetDefaultConfig() {
  return window['go']['app']['App']['GetDefaultConfig']();
}

export function GetInstalledMods(arg1) {
  return window['go']['app']['App']['GetInstalledMods'](arg1);
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetModDetail(arg1, arg2) {
  return window['go']['app']['App']['GetModDetail'](arg1, arg2);
}

export function GetProcessInfo(arg1) {
  return window['go']['app']['App']['GetProcessInfo'](arg1);
}

export function GetProfiles(arg1) {
  return window['go']['app']['App']['GetProfiles'](arg1);
}

export function GetServerPID() {
  return window['go']['app']['App']['GetServerPID']();
}

export function GetServers() {
  return window['go']['app']['App']['GetServers']();
}

export function GetSystemInfo() {
  return window['go']['app']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function InstallBepInEx(arg1) {
  return window['go']['app']['App']['InstallBepInEx'](arg1);
}

export function InstallMod(arg1, arg2, arg3) {
  return window['go']['app']['App']['InstallMod'](arg1, arg2, arg3);
}

export function InstallSteamCMD() {
  return window['go']['app']['App']['InstallSteamCMD']();
}

export function InstallValheimServer(arg1) {
  return window['go']['app']['App']['InstallValheimServer'](arg1);
}

export function IsBepInExInstalled(arg1) {
  return window['go']['app']['App']['IsBepInExInstalled'](arg1);
}

export function IsServerRunning() {
  return window['go']['app']['App']['IsServerRunning']();
}

export function IsSteamCMDInstalled() {
  return window['go']['app']['App']['IsSteamCMDInstalled']();
}

export function ListBackups(arg1) {
  return window['go']['app']['App']['ListBackups'](arg1);
}

export function LoadServerConfig(arg1) {
  return window['go']['app']['App']['LoadServerConfig'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['app']['App']['RestoreBackup'](arg1, arg2);
}

export function RunSafetyChecks(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RunSafetyChecks'](arg1, arg2, arg3, arg4);
}

export function SaveServerConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveServerConfig'](arg1, arg2);
}

export function SearchMods(arg1, arg2) {
  return window['go']['app']['App']['SearchMods'](arg1, arg2);
}

export function SetLogPaused(arg1) {
  return window['go']['app']['App']['SetLogPaused'](arg1);
}

export function SetModEnabled(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetModEnabled'](arg1, arg2, arg3);
}

export function StartServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['StartServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StopServer() {
  return window['go']['app']['App']['StopServer']();
}

export function UninstallMod(arg1, arg2) {
  return window['go']['app']['App']['UninstallMod'](arg1, arg2);
}

export function UpdateServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateServer'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateServerPath(arg1) {
  return window['go']['app']['App']['ValidateServerPath'](arg1);
}
