// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateServer'](arg1, arg2, arg3, arg4);
}

export function DeleteServer(arg1) {
  return window['go']['app']['App']['DeleteServer'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetServers() {
  return window['go']['app']['App']['GetServers']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function UpdateServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateServer'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateServerPath(arg1) {
  return window['go']['app']['App']['ValidateServerPath'](arg1);
}
